version: '3.4'

services: 

  frontend:
    image: onlinestorefrontend
    build:
      context: frontend
      dockerfile: Dockerfile
    environment: 
      - backendUrl=http://backend
    ports:
      - "5067:80"
    depends_on: 
      - backend


  backend:
    image: onlinestorebackend
    build: 
      context: backend
      dockerfile: Dockerfile
    ports: 
      - "5021:80"